# Generated by Django 2.0.7 on 2018-08-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(max_length=8192, unique=True, verbose_name='链接')),
                ('short_code', models.TextField(unique=True, verbose_name='短代码')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='创建更改时间')),
                ('end_time', models.DateTimeField(verbose_name='失效时间')),
            ],
        ),
    ]
